from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start'
        self.MirrorCommand = f'mirror{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirror{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'list{CMD_INDEX}'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f'status{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users'
        self.AuthorizeCommand = f'authorize'
        self.UnAuthorizeCommand = f'unauthorize'
        self.AddSudoCommand = f'addsudo'
        self.RmSudoCommand = f'rmsudo'
        self.PingCommand = f'ping'
        self.RestartCommand = f'restart'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HStatsCommand = f'hstats'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log'
        self.CloneCommand = f'clone{CMD_INDEX}'
        self.CountCommand = f'count'
        self.WatchCommand = f'watch{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell'
        self.ExecHelpCommand = f'exechelp'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'leech{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch'
        self.LeechZipWatchCommand = f'leechzipwatch'
        self.RssListCommand = f'rsslist'
        self.RssGetCommand = f'rssget'
        self.RssSubCommand = f'rsssub'
        self.RssUnSubCommand = f'rssunsub'
        self.RssSettingsCommand = f'rssset'
        self.EvalCommand = f'eval'
        self.ExecCommand = f'exec'
        self.WayBackCommand = 'wayback'
        self.ClearLocalsCommand = f'clearlocals'

BotCommands = _BotCommands()
