from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = "start"
        self.MirrorCommand = f"mirror{CMD_INDEX}"
        self.UnzipMirrorCommand = f"unzipmirror{CMD_INDEX}"
        self.ZipMirrorCommand = f"zipmirror{CMD_INDEX}"
        self.CancelMirror = f"cancel{CMD_INDEX}"
        self.CancelAllCommand = f"cancelall{CMD_INDEX}"
        self.ListCommand = f"list{CMD_INDEX}"
        self.SearchCommand = f"search{CMD_INDEX}"
        self.StatusCommand = f"status{CMD_INDEX}"
        self.AuthorizedUsersCommand = "users"
        self.AuthorizeCommand = "authorize"
        self.UnAuthorizeCommand = "unauthorize"
        self.AddSudoCommand = "addsudo"
        self.RmSudoCommand = "rmsudo"
        self.PingCommand = "ping"
        self.RestartCommand = "restart"
        self.StatsCommand = f"stats{CMD_INDEX}"
        self.HStatsCommand = "hstats"
        self.HelpCommand = f"help{CMD_INDEX}"
        self.LogCommand = "log"
        self.CloneCommand = f"clone{CMD_INDEX}"
        self.CountCommand = "count"
        self.WatchCommand = f"watch{CMD_INDEX}"
        self.ZipWatchCommand = f"zipwatch{CMD_INDEX}"
        self.QbMirrorCommand = f"qbmirror{CMD_INDEX}"
        self.QbUnzipMirrorCommand = f"qbunzipmirror{CMD_INDEX}"
        self.QbZipMirrorCommand = f"qbzipmirror{CMD_INDEX}"
        self.DeleteCommand = f"del{CMD_INDEX}"
        self.ShellCommand = "shell"
        self.ExecHelpCommand = "exechelp"
        self.LeechSetCommand = f"leechset{CMD_INDEX}"
        self.SetThumbCommand = f"setthumb{CMD_INDEX}"
        self.LeechCommand = f"leech{CMD_INDEX}"
        self.UnzipLeechCommand = f"unzipleech{CMD_INDEX}"
        self.ZipLeechCommand = f"zipleech{CMD_INDEX}"
        self.QbLeechCommand = f"qbleech{CMD_INDEX}"
        self.QbUnzipLeechCommand = f"qbunzipleech{CMD_INDEX}"
        self.QbZipLeechCommand = f"qbzipleech{CMD_INDEX}"
        self.LeechWatchCommand = "leechwatch"
        self.LeechZipWatchCommand = "leechzipwatch"
        self.RssListCommand = "rsslist"
        self.RssGetCommand = "rssget"
        self.RssSubCommand = "rsssub"
        self.RssUnSubCommand = "rssunsub"
        self.RssSettingsCommand = "rssset"
        self.EvalCommand = "eval"
        self.ExecCommand = "exec"
        self.WayBackCommand = "wayback"
        self.ClearLocalsCommand = "clearlocals"


BotCommands = _BotCommands()
